name: palman
description: Приложение для торговых представителей
publish_to: 'none'
version: 1.1.7+39

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cross_file: ^0.3.3
  crypto: ^3.0.3
  collection: ^1.17.1
  dio: ^5.2.1
  drift: ^2.13.1
  easy_refresh: ^3.3.2
  equatable: ^2.0.5
  expansion_tile_group: ^1.2.3
  file: ^6.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.7.0
  geolocator: ^9.0.2
  holding_gesture: ^1.2.0
  http: ^0.13.6
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.9
  provider: ^6.0.5
  pub_semver: ^2.1.1
  queue: ^3.1.0+2
  quiver: ^3.0.1
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  sentry_flutter: ^7.7.0
  sqlite3_flutter_libs: ^0.5.0
  u_app_utils:
    git:
      url: git@github.com:Unact/u_app_utils.git
      ref: 28b84e8
  uuid: ^3.0.7
  yandex_mapkit: ^3.3.3

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
  min_sdk_android: 21

flutter:
  assets:
    - assets/placeicon.png
    - assets/filled_placeicon.png
    - assets/not_filled_placeicon.png
  uses-material-design: true
