name: palman
description: Приложение для торговых представителей
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  animated_tree_view: ^2.1.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5
  cross_file: ^0.3.3
  collection: ^1.17.1
  device_info_plus: ^9.0.2
  dio: ^5.2.1
  drift: ^2.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_image_compress: ^2.0.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_typeahead: ^4.6.2
  fk_user_agent: ^2.1.0
  geolocator: ^9.0.2
  intl: ^0.18.0
  keyboard_actions: ^4.2.0
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  pub_semver: ^2.1.1
  quiver: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^7.7.0
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.0.20
  uuid: ^3.0.7
  yandex_mapkit: ^3.3.3

dev_dependencies:
  build_runner: ^2.4.5
  drift_dev: ^2.9.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/placeicon.png
  uses-material-design: true
